### ISSUE TITLE
tests/debug_weather.rs fails to compile on rustc 1.95.0 (pre-existing on main)

### ISSUE THREAD

**Issue by anchapin** [anchapin/fluxion#789]
## Bug Description

\`tests/debug_weather.rs\` has two compile errors that prevent it from building with rustc 1.95.0 (used in CI). The file is broken on \`origin/main\`.

### Error 1: \`get_hourly_data\` returns \`Result\`, not \`Option\`
\`\`\`
error[E0308]: mismatched types
  --> tests/debug_weather.rs:14:16
   |
14 |         if let Some(data) = weather.get_hourly_data(hour) {
   |                ^^^^^^^^^   ----------------------------- this expression has type \`Result<HourlyWeatherData, WeatherError>\`
\`\`\`

The \`WeatherSource::get_hourly_data()\` method returns \`Result<HourlyWeatherData, WeatherError>\`, but the test uses \`if let Some(data)\`.

### Error 2: \`{:f}\`/\`{:g}\` float format traits removed in rustc 1.95.0
\`\`\`
error: unknown format trait \`f\`
  --> tests/debug_weather.rs:17:43
17 |                 \"Hour {:3}: dry_bulb={:6.1f}°C, ...
error: unknown format trait \`g\`
  --> tests/debug_weather.rs:17:43
17 |                 \"Hour {:3}: dry_bulb={:6.1g}°C, ...
\`\`\`

The \`f\` and \`g\` format traits were removed in rustc 1.95.0. The only valid float formatting traits are \`\` (Display), \`?\` (Debug), \`e\` (LowerExp), \`E\` (UpperExp).

## Impact

- Blocks \`python-examples\` CI job on any PR that compiles test targets
- Affects PRs: #772, others that have \`tests/debug_weather.rs\` in their diff

## Fix Applied

Fixed in PR #772 branch \`fix/741-sol-air-lw-shgc-fd-h\` (commit 404c932):
- Changed \`if let Some(data)\` → \`if let Ok(data)\`
- Removed \`{:f}\`/\`{:g}\` width specifiers; used bare \`{}\` with default Display formatting

## Action Needed

Apply the same fix to \`origin/main\` so all PRs inherit a clean baseline.

**Comment by anchapin** [comment]
> *This was generated by AI during triage.*

## Verify-and-close — issue is stale

`tests/debug_weather.rs` compiles cleanly on rustc 1.95.0 against current `main` (HEAD `6feeb51`):

```
$ rustc --version
rustc 1.95.0 (59807616e 2026-04-14)

$ cargo build --tests
   Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.03s

$ cargo clippy --tests -- -D warnings
   Finished `dev` profile [unoptimized + debuginfo] target(s) in 10.47s

$ cargo test --no-run --test debug_weather
   Finished `test` profile [unoptimized + debuginfo] target(s) in 0.18s
   Executable tests/debug_weather.rs (target/debug/deps/debug_weather-02c26e4081f662a9)
```

The file already uses `if let Ok(data) = weather.get_hourly_data(hour)` (matching the `Result<HourlyWeatherData, WeatherError>` return type) and the simplified format strings.

`git log -- tests/debug_weather.rs` shows the fix landed in commit `404c932` — `fix(tests): debug_weather.rs - Result instead of Option, simpler float formatting`.

Closing as resolved by prior work; no PR required.
