### ISSUE TITLE
bug(ci): 'Workspace Check' job does not include '--examples' — example drift (#3125) is silent

### ISSUE THREAD

**Issue by anchapin** [anchapin/fluxion#3125]
## Bug

The canonical `Workspace Check (GH)` listener at `.github/workflows/rust-tests.yml::workspace-check-gh` runs:

```
cargo check --workspace --verbose
```

But `cargo check --workspace` does **not** check examples by default. So the 4 broken examples in #3125 (`examples/multi_zone_demo.rs`, `examples/debug_solar_case_600.rs`, `examples/tutorial_custom_model.rs`, `examples/test_6r2c.rs`) — all of which fail with `error[E0609]: no field ... on type ThermalModel<VectorField>` — went undetected through multiple drift-detection scripts (`scripts/check_architecture_drift.py`, `scripts/check_doc_drift.py`, `scripts/check_stub_modules.py`, `scripts/check_orphan_modules.py`).

## Why this matters

- `examples/*.rs` are user-facing documentation. They drift silently — once a field/method is renamed, the example stops compiling but no required check fires.
- The drift is recoverable: a quick `cargo check --examples` would have caught all 25 errors immediately. The gap is purely CI scope.
- Workspace Check is the canonical "did any sibling crate regress?" gate. Examples are the canonical "does the public API still compile for users?" gate. They're different and both needed.

## Acceptance

- Add `--examples --all-targets` to the `cargo check` invocation in the `workspace-check-gh` (and `workspace-check-hz`) jobs.
- Verify the resulting `cargo check --workspace --examples --all-targets --verbose` exits 0 against current `develop` after #3125 is fixed.
- Add an `informational` (non-required-check) test-harness assertion that the example count is non-empty (`ls examples/*.rs | wc -l ≥ 5`) so a future "let's delete examples/*.rs" cleanup can't silently shrink the public surface.

Refs #3125 (the symptom this gap lets slip through)
